name: Test Job
on: 
  workflow_call:
    inputs:
        python_version:
          type: string
        test_file:
          type: string

jobs:
  test_reusable: 
    runs-on: ubuntu-latest 
    steps:
      - name: Get Code
        uses: actions/checkout@v7
      - name: install Python 
        uses: actions/setup-python@v6
        with:
          python-version: ${{inputs.python_version}} 
      - name: caching requirments
        uses: actions/cache@v4
        with:
          path: ~/cache/pip
          key: pip-${{hashFiles('requirements.txt')}}          
      - name: install requirments
        run: pip install -r requirements.txt
      - name: run test data quality 
        run: pytest ${{inputs.test_file}}